# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog
email: alex@alexsamuel.net

destination: docs
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://alexhsamuel.github.io"
# twitter_username: jekyllrb
github_username:  alexhsamuel
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown

description: |
  Alex Samuel's blog.



